spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${MYSQL_URL}
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      database: famila
