spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      host: ${MONGODB_HOST}
      database: famila
  cloud:
    aws:
      stack.auto: false
      region: ap-northeast-2
      credentials:
        accessKey: testAccessKey
        secretKey: testSecretKey
      s3:
        bucket: testBucket

jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: admin
  expiration-second: 1800
